mc_LJ: include/logger.h File Reference
logger.h File Reference
Header file for managing logging, see #logger.c.
#include <stdint.h>
Enumerations
enum LOG_LEVELS {
LOG_NOTHING = 0, LOG_ERROR = 1, LOG_WARNING = 2, LOG_INFO = 3,
LOG_DEBUG = 4
}
The available logging Levels.
Functions
void init_logfiles ()
Prepares LOGGING I/O if necessary, depending of the value of #LOG_SEVERITY.
void close_logfiles ()
Before exiting the program, closes properly the logging files.
char * get_loglevel_string ()
Returns a string corresponding to the logging level.
char * get_time ()
Puts in a string the current date, and returns it.
uint32_t LOG_PRINT (LOG_LEVELS mesg_severity, char *fmt,...)
log_print
uint32_t LOG_PRINT_SHORT (LOG_LEVELS mesg_severity, char *fmt,...)
Same as LOG_PRINT but without the date appended at the beginning of the line.
Variables
LOG_LEVELS LOG_SEVERITY
Detailed Description
Header file for managing logging, see #logger.c.
Authors
Florent Hedin (University of Basel, Switzerland)
Markus Meuwly (University of Basel, Switzerland)
Copyright
Copyright (c) 2013, Florent Hedin, Markus Meuwly, and the University of Basel.
All rights reserved.
The 3-clause BSD license is applied to this software.
See LICENSE.txt
Definition in file logger.h.
Enumeration Type Documentation
enum LOG_LEVELS
The available logging Levels.
This will control what is written to logging files ; those files are named :
error.log
warning.log
info.log
debug.log
The higher the level, the more text is written to those text files, so be careful with long simulations coupled to high levels of logging.
The different levels, members of the enum LOG_LEVELS are :
LOG_NOTHING : At this level there is no logging at all.
LOG_ERROR : An Error is a critical event which will cause the program to abort immediately, for example a missing parameter for which no default value is provided.
LOG_WARNING : A Warning is a non-critical event, i.e. the event is just reported but the program execution continues, for example a missing or wrong parameter for which a default value is going to be used.
LOG_INFO : An Info message reports to the user a possibly useful information, an event with no consequence for the simulation. For example, that the trajectory was succesfully written as planed.
LOG_DEBUG : A debug message is really technical and verbose, for example dumping a variable. This should be enabled for bug tracking.
The logging is progressive, enabling LOG_INFO means that higher levels LOG_ERROR and LOG_WARNING are also enabled.
The default is set to LOG_WARNING.
Enumerator
LOG_NOTHING
No log file is created : this is not recommended as no information is reported
LOG_ERROR
Only errors are reported to error.log
LOG_WARNING
Warnings are reported to warning.log , and also errors to error.log. This is the default.
LOG_INFO
Info messages are reported to info.log , and also warnings and errors to their respective files.
LOG_DEBUG
A large amount of debugging messages are written to debug.log . The previous levels are still written to their respective files.
Definition at line 54 of file logger.h.
 {
     LOG_NOTHING = 0,
     LOG_ERROR = 1,
     LOG_WARNING = 2,
     LOG_INFO = 3,
     LOG_DEBUG = 4
 } LOG_LEVELS;
Function Documentation
char* get_loglevel_string ()
Returns a string corresponding to the logging level.
Returns
An array of char containing the description of the logging level, for example "LOG_ERROR"
Definition at line 72 of file logger.c.
References LOG_DEBUG, LOG_ERROR, LOG_INFO, LOG_NOTHING, and LOG_WARNING.
Referenced by main().
 {
     char* str_log=NULL;
     switch(LOG_SEVERITY)
     {
     case LOG_NOTHING:
         str_log = "LOG_NOTHING";
         break;
     case LOG_ERROR:
         str_log = "LOG_ERROR";
         break;
     case LOG_WARNING:
         str_log = "LOG_WARNING";
         break;
     case LOG_INFO:
         str_log = "LOG_INFO";
         break;
     case LOG_DEBUG:
         str_log = "LOG_DEBUG";
         break;
     default:
         str_log = "UNKNOWN";
         break;
     }
     return str_log;
 }
char* get_time ()
Puts in a string the current date, and returns it.
This function returns the date with the following format :
DAY/MONTH/YEAR-HH:MM:SS
For example : 17/10/2013-16:26:36
Returns
A character string filled with the date and hour
Definition at line 139 of file logger.c.
Referenced by main().
 {
     static char date[32];
     struct tm * timeinfo;
     time_t newtime;
     time(&newtime);
     timeinfo = localtime(&newtime);
     strftime(date,32,"%d/%b/%Y-%H:%M:%S",timeinfo);
     return date;
 }
uint32_t LOG_PRINT (LOG_LEVELS mesg_severity, char * fmt, ...)
log_print
Parameters
mesg_severity
fmt
...
Definition at line 160 of file logger.c.
References LOG_DEBUG, LOG_ERROR, LOG_INFO, and LOG_WARNING.
Referenced by main().
 {
     // if the severity of the current message is at least equal to the gloval level we print it
     if (mesg_severity <= LOG_SEVERITY)
     {
         va_list list;
         FILE *FP=NULL;
         static char event_date[32]="";
         char message[50]="";
         // get the date string
         get_time_ptr(event_date);
         // depending of the severity, chose the correct file for writting
         switch(mesg_severity)
         {
         case LOG_ERROR:
             FP = F_ERROR;
             sprintf(message,"[Error @ ");
             break;
         case LOG_WARNING:
             FP = F_WARN;
             sprintf(message,"[Warning @ ");
             break;
         case LOG_INFO:
             FP = F_INFO;
             sprintf(message,"[Info @ ");
             break;
         case LOG_DEBUG:
             FP = F_DEBUG;
             sprintf(message,"[Debug @ ");
             break;
         default:
             return -1;
             break;
         }
         // write date contained in event_date to message
         strncat(message,event_date,32);
         strncat(message,"]\t",2);
         // print message to file
         fprintf(FP,"%s",message);
         // prepare processing of the variable arguments list
         // fmt is the last non-optional argument
         va_start(list,fmt);
         // now forward what have to be printed to vfprintf
         vfprintf(FP,fmt,list);
         va_end(list);
         return 0;
     } // end of if (mesg_severity >= LOG_SEVERITY)
     return 1;
 }
uint32_t LOG_PRINT_SHORT (LOG_LEVELS mesg_severity, char * fmt, ...)
Same as LOG_PRINT but without the date appended at the beginning of the line.
Parameters
mesg_severity
fmt
...
Definition at line 234 of file logger.c.
References LOG_DEBUG, LOG_ERROR, LOG_INFO, and LOG_WARNING.
 {
     // if the severity of the current message is at least equal to the gloval level we print it
     if (mesg_severity <= LOG_SEVERITY)
     {
         va_list list;
         FILE *FP=NULL;
         // depending of the severity, chose the correct file for writting
         switch(mesg_severity)
         {
         case LOG_ERROR:
             FP = F_ERROR;
             break;
         case LOG_WARNING:
             FP = F_WARN;
             break;
         case LOG_INFO:
             FP = F_INFO;
             break;
         case LOG_DEBUG:
             FP = F_DEBUG;
             break;
         default:
             return -1;
             break;
         }
         // prepare processing of the variable arguments list
         // fmt is the last non-optional argument
         va_start(list,fmt);
         // now forward what have to be printed to vfprintf
         vfprintf(FP,fmt,list);
         va_end(list);
         return 0;
     } // end of if (mesg_severity >= LOG_SEVERITY)
     return 1;
 }